version: '3.8'

services:
  bot-server:
    build:
      context: .             # Dockerfile이 있는 위치 (루트 or bot-server/)
      dockerfile: Dockerfile
    container_name: discord-bot
    restart: always
    env_file:
      - .env                 # .env 파일로 환경 변수 전달
    volumes:
      - .:/app               # 선택: 로컬 소스 실시간 반영용 (개발 시)
    working_dir: /app
    command: node app.js     # app.js가 진입점일 경우
    ports:
      - "3000:3000"          # 필요에 따라 포트 매핑 (예시: 3000번 포트)