version: '3.8'

services:
  discord-bot:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: discord-bot
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules 